/**
 * Master listing / Google labels → Provesio /hotel/search country names.
 * Values must match vendorCountry in lib/data/provesio-city-allowlist.json
 * (VAL-004: "Invalid country name (Example: India)").
 */

const ISO2_TO_PROVESIO = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua And Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BQ: "Bonaire St Eustatius And Saba",
  BA: "Bosnia And Herzegovina",
  BW: "Botswana",
  BR: "Brazil",
  VG: "British Vergin Islands",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CC: "Cocos (Keeling) Island",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CD: "Democratic Republic of the Congo",
  CK: "Cook Islands",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CW: "Curacao",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  SZ: "Eswatini",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GN: "Guinea",
  GW: "Guinea Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HN: "Honduras",
  HK: "Hongkong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IQ: "Iraq",
  IE: "Ireland",
  IL: "Israel",
  IT: "Italy",
  CI: "Ivory Coast",
  JM: "Jamaica",
  JP: "Japan",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  XK: "Kosovo",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Islands",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestinian Occ. Territories",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russia",
  RW: "Rwanda",
  BL: "Saint Barth",
  SH: "Saint Helena",
  KN: "Saint Kitts And Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  SX: "Saint Maarten",
  VC: "Saint Vincent And The Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome And Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  KR: "South Korea",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SE: "Sweden",
  CH: "Switzerland",
  TW: "Taiwan",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  TG: "Togo",
  TO: "Tonga",
  TT: "Trinidad And Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks And Caicos Islands",
  VI: "U.S. Virgin Islands",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  GB: "United Kingdom",
  US: "United States",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  WF: "Wallis & Futuna Islands",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

/** Google / UI / official labels → Provesio vendorCountry (lookup is lowercased). */
const LISTING_COUNTRY_TO_PROVESIO = {
  "hong kong": "Hongkong",
  hongkong: "Hongkong",
  "hong kong, (sar) china": "Hongkong",
  "hong kong sar": "Hongkong",
  macau: "Macao",
  macao: "Macao",
  "macao, (sar) china": "Macao",
  "korea, republic of": "South Korea",
  "republic of korea": "South Korea",
  korea: "South Korea",
  "south korea": "South Korea",
  "korea, democratic peoples republic of": "North Korea",
  "st. christopher (st. kitts) nevis": "Saint Kitts And Nevis",
  "saint kitts and nevis": "Saint Kitts And Nevis",
  "st kitts and nevis": "Saint Kitts And Nevis",
  "virgin islands, united states": "U.S. Virgin Islands",
  "us virgin islands": "U.S. Virgin Islands",
  "u.s. virgin islands": "U.S. Virgin Islands",
  "united states virgin islands": "U.S. Virgin Islands",
  "british virgin islands": "British Vergin Islands",
  "virgin islands, british": "British Vergin Islands",
  uae: "United Arab Emirates",
  "u.a.e.": "United Arab Emirates",
  "united arab emirates": "United Arab Emirates",
  "bosnia herzegovina": "Bosnia And Herzegovina",
  "bosnia and herzegovina": "Bosnia And Herzegovina",
  "brunei darussalam": "Brunei",
  "chinese taipei": "Taiwan",
  "cote d'ivoire": "Ivory Coast",
  "côte d'ivoire": "Ivory Coast",
  "ivory coast": "Ivory Coast",
  "lao peoples democratic republic": "Laos",
  "lao people's democratic republic": "Laos",
  "libyan arab jamahiriya": "Libya",
  moldovo: "Moldova",
  "republic of moldova": "Moldova",
  monserrat: "Montserrat",
  "republic of macedonia": "Macedonia",
  "north macedonia": "Macedonia",
  "republic of serbia": "Serbia",
  reunion: "Reunion",
  réunion: "Reunion",
  "russian federation": "Russia",
  "syrian arab republic": "Syria",
  "united republic of tanzania": "Tanzania",
  "viet nam": "Vietnam",
  vietnam: "Vietnam",
  "wallis and futuna": "Wallis & Futuna Islands",
  "wallis and futuna islands": "Wallis & Futuna Islands",
  "st. lucia": "Saint Lucia",
  "st lucia": "Saint Lucia",
  "saint lucia": "Saint Lucia",
  "st. pierre and miquelon": "Saint Pierre and Miquelon",
  "st. vincent and the grenadines": "Saint Vincent And The Grenadines",
  "saint vincent and the grenadines": "Saint Vincent And The Grenadines",
  "democratic republic of the congo": "Democratic Republic of the Congo",
  "congo, democratic republic of the": "Democratic Republic of the Congo",
  "congo-kinshasa": "Democratic Republic of the Congo",
  "congo-brazzaville": "Congo",
  "republic of the congo": "Congo",
  türkiye: "Turkey",
  Türkiye: "Turkey",
  turkiye: "Turkey",
  turkey: "Turkey",
  czechia: "Czech Republic",
  "czech republic": "Czech Republic",
  burma: "Myanmar",
  myanmar: "Myanmar",
  eswatini: "Eswatini",
  swaziland: "Swaziland",
  uk: "United Kingdom",
  "great britain": "United Kingdom",
  britain: "United Kingdom",
  "united kingdom": "United Kingdom",
  usa: "United States",
  "u.s.a.": "United States",
  "united states of america": "United States",
  america: "United States",
  "united states": "United States",
  palestine: "Palestinian Occ. Territories",
  "palestinian territories": "Palestinian Occ. Territories",
  "palestinian occupied territories": "Palestinian Occ. Territories",
  "state of palestine": "Palestinian Occ. Territories",
  "cayman islands": "Cayman",
  "cabo verde": "Cape Verde",
  "cape verde": "Cape Verde",
  "guinea-bissau": "Guinea Bissau",
  "guinea bissau": "Guinea Bissau",
  "trinidad and tobago": "Trinidad And Tobago",
  "antigua and barbuda": "Antigua And Barbuda",
  "sao tome and principe": "Sao Tome And Principe",
  "são tomé and príncipe": "Sao Tome And Principe",
  "turks and caicos islands": "Turks And Caicos Islands",
  "turks and caicos": "Turks And Caicos Islands",
  "saint barthélemy": "Saint Barth",
  "saint barthelemy": "Saint Barth",
  "st barthelemy": "Saint Barth",
  "sint maarten": "Saint Maarten",
  "st maarten": "Saint Maarten",
  "saint martin": "Saint Martin",
  holland: "Netherlands",
  "the netherlands": "Netherlands",
  "korea, south": "South Korea",
};

function lookupAlias(raw) {
  const key = String(raw || "").trim().toLowerCase();
  if (!key) return null;
  return LISTING_COUNTRY_TO_PROVESIO[key] || null;
}

function lookupIso2(countryCode) {
  const code = String(countryCode ?? "").trim().toUpperCase();
  if (!/^[A-Z]{2}$/.test(code)) return null;
  return ISO2_TO_PROVESIO[code] || null;
}

export function toProvesioHotelCountry(country, countryCode) {
  const fromCode = lookupIso2(countryCode);
  if (fromCode) return fromCode;

  const raw = String(country ?? "").trim();
  if (!raw) return raw;

  const aliasedFromLabel = lookupAlias(raw);
  if (aliasedFromLabel) return aliasedFromLabel;

  const commaIso = raw.match(/^(.+?),\s*([A-Za-z]{2})$/);
  if (commaIso) {
    const fromEmbeddedCode = lookupIso2(commaIso[2]);
    if (fromEmbeddedCode) return fromEmbeddedCode;
    const fromHead = lookupAlias(commaIso[1]);
    if (fromHead) return fromHead;
  }

  const commaParen = raw.match(/^([^,]+),\s*\(/);
  if (commaParen?.[1]) {
    const head = commaParen[1].trim();
    return lookupAlias(head) || head;
  }

  return raw;
}
